# This is a basic workflow to help you get started with Actions

name: Development build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install depedencies
      - name: Install depedencies
        run: npm install

      - name: Migrate contract to rinkeby
        run: npm run migrate_rinkeby
        env:
          WALLET_SECRET_KEY: ${{ secrets.WALLET_SECRET_KEY }}
          ARB_PROVIDER_RINKEBY: ${{ secrets.ARB_PROVIDER_RINKEBY }}
        
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'dev-contract-abi'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'    # optional: defaults to us-east-1
          SOURCE_DIR: 'build/contracts' # optional: defaults to entire repository
      
